# jqplot
<div id="chart" class="jqplot-target" style="position: relative;">

<canvas width="400" height="400" class="jqplot-base-canvas" style="position: absolute; left: 0px; top: 0px;"></canvas><div class="jqplot-title" style="position: absolute; top: 0px; left: 0px; width: 400px; text-align: center;">Line Style Options</div><div class="jqplot-axis jqplot-xaxis" style="position: absolute; width: 400px; height: 15px; left: 0px; bottom: 0px;"><div class="jqplot-xaxis-tick" style="position: absolute; left: 24px;">-1</div><div class="jqplot-xaxis-tick" style="position: absolute; left: 71.125px;">0</div><div class="jqplot-xaxis-tick" style="position: absolute; left: 116.25px;">1</div><div class="jqplot-xaxis-tick" style="position: absolute; left: 161.375px;">2</div><div class="jqplot-xaxis-tick" style="position: absolute; left: 206.5px;">3</div><div class="jqplot-xaxis-tick" style="position: absolute; left: 251.625px;">4</div><div class="jqplot-xaxis-tick" style="position: absolute; left: 296.75px;">5</div><div class="jqplot-xaxis-tick" style="position: absolute; left: 341.875px;">6</div><div class="jqplot-xaxis-tick" style="position: absolute; left: 387px;">7</div></div><div class="jqplot-axis jqplot-yaxis" style="position: absolute; height: 400px; width: 19px; left: 0px; top: 0px;"><div class="jqplot-yaxis-tick" style="position: absolute; top: 367.5px;">-1.5</div><div class="jqplot-yaxis-tick" style="position: absolute; top: 310.333px;">-1.0</div><div class="jqplot-yaxis-tick" style="position: absolute; top: 253.167px;">-0.5</div><div class="jqplot-yaxis-tick" style="position: absolute; top: 196px;">0.0</div><div class="jqplot-yaxis-tick" style="position: absolute; top: 138.833px;">0.5</div><div class="jqplot-yaxis-tick" style="position: absolute; top: 81.6667px;">1.0</div><div class="jqplot-yaxis-tick" style="position: absolute; top: 24.5px;">1.5</div></div><canvas width="400" height="400" class="jqplot-grid-canvas" style="position: absolute; left: 0px; top: 0px;"></canvas><canvas width="361" height="343" class="jqplot-series-shadowCanvas" style="position: absolute; left: 29px; top: 32px;"></canvas><canvas width="361" height="343" class="jqplot-series-canvas" style="position: absolute; left: 29px; top: 32px;"></canvas><canvas width="361" height="343" class="jqplot-highlight-canvas" style="position: absolute; left: 29px; top: 32px;"></canvas><div class="jqplot-highlighter-tooltip" style="position: absolute; display: none;"></div><div class="jqplot-cursor-tooltip" style="position: absolute; left: 196px; top: 62px; display: block;">161, 24</div><canvas width="361" height="343" class="jqplot-lineRenderer-highlight-canvas" style="position: absolute; left: 29px; top: 32px;"></canvas><canvas width="361" height="343" class="jqplot-event-canvas" style="position: absolute; left: 29px; top: 32px; cursor: crosshair;"></canvas></div>
<input id="buttonPrev" type="button" value="Prev">
<input id="buttonNext" type="button" value="Next">


<link class="include" rel="stylesheet" type="text/css" href="libs/jqplot/jquery.jqplot.min.css"  


<script type="text/javascript" src="libs/jqPlot/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="libs/plugins/jqplot.canvasTextRenderer.min.js"></script>
<script type="text/javascript" src="libs/jqPlot/plugins/jqplot.canvasAxisLabelRenderer.min.js"></script>
<script type="text/javascript" src="libs/jqPlot/plugins/jqplot.highlighter.min.js"></script>
<script type="text/javascript" src="libs/jqPlot/plugins/jqplot.cursor.min.js"></script>
    
  

<style type="text/css">
#chart {
  width: 400px;
  height: 400px;
}

//jquery.jqplot.css

/*rules for the plot target div.  These will be cascaded down to all plot elements according to css rules*/

.jqplot-target {
  position: relative;
  color: #666666;
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  font-size: 1em;
  /*    height: 300px;
    width: 400px;*/
}


/*rules applied to all axes*/

.jqplot-axis {
  font-size: 0.75em;
}

.jqplot-xaxis {
  margin-top: 10px;
}

.jqplot-x2axis {
  margin-bottom: 10px;
}

.jqplot-yaxis {
  margin-right: 10px;
}

.jqplot-y2axis,
.jqplot-y3axis,
.jqplot-y4axis,
.jqplot-y5axis,
.jqplot-y6axis,
.jqplot-y7axis,
.jqplot-y8axis,
.jqplot-y9axis,
.jqplot-yMidAxis {
  margin-left: 10px;
  margin-right: 10px;
}


/*rules applied to all axis tick divs*/

.jqplot-axis-tick,
.jqplot-xaxis-tick,
.jqplot-yaxis-tick,
.jqplot-x2axis-tick,
.jqplot-y2axis-tick,
.jqplot-y3axis-tick,
.jqplot-y4axis-tick,
.jqplot-y5axis-tick,
.jqplot-y6axis-tick,
.jqplot-y7axis-tick,
.jqplot-y8axis-tick,
.jqplot-y9axis-tick,
.jqplot-yMidAxis-tick {
  position: absolute;
  white-space: pre;
}

.jqplot-xaxis-tick {
  top: 0px;
  /* initial position untill tick is drawn in proper place */
  left: 15px;
  /*    padding-top: 10px;*/
  vertical-align: top;
}

.jqplot-x2axis-tick {
  bottom: 0px;
  /* initial position untill tick is drawn in proper place */
  left: 15px;
  /*    padding-bottom: 10px;*/
  vertical-align: bottom;
}

.jqplot-yaxis-tick {
  right: 0px;
  /* initial position untill tick is drawn in proper place */
  top: 15px;
  /*    padding-right: 10px;*/
  text-align: right;
}

.jqplot-yaxis-tick.jqplot-breakTick {
  right: -20px;
  margin-right: 0px;
  padding: 1px 5px 1px 5px;
  /*    background-color: white;*/
  z-index: 2;
  font-size: 1.5em;
}

.jqplot-y2axis-tick,
.jqplot-y3axis-tick,
.jqplot-y4axis-tick,
.jqplot-y5axis-tick,
.jqplot-y6axis-tick,
.jqplot-y7axis-tick,
.jqplot-y8axis-tick,
.jqplot-y9axis-tick {
  left: 0px;
  /* initial position untill tick is drawn in proper place */
  top: 15px;
  /*    padding-left: 10px;*/
  /*    padding-right: 15px;*/
  text-align: left;
}

.jqplot-yMidAxis-tick {
  text-align: center;
  white-space: nowrap;
}

.jqplot-xaxis-label {
  margin-top: 10px;
  font-size: 11pt;
  position: absolute;
}

.jqplot-x2axis-label {
  margin-bottom: 10px;
  font-size: 11pt;
  position: absolute;
}

.jqplot-yaxis-label {
  margin-right: 10px;
  /*    text-align: center;*/
  font-size: 11pt;
  position: absolute;
}

.jqplot-yMidAxis-label {
  font-size: 11pt;
  position: absolute;
}

.jqplot-y2axis-label,
.jqplot-y3axis-label,
.jqplot-y4axis-label,
.jqplot-y5axis-label,
.jqplot-y6axis-label,
.jqplot-y7axis-label,
.jqplot-y8axis-label,
.jqplot-y9axis-label {
  /*    text-align: center;*/
  font-size: 11pt;
  margin-left: 10px;
  position: absolute;
}

.jqplot-meterGauge-tick {
  font-size: 0.75em;
  color: #999999;
}

.jqplot-meterGauge-label {
  font-size: 1em;
  color: #999999;
}

table.jqplot-table-legend {
  margin-top: 12px;
  margin-bottom: 12px;
  margin-left: 12px;
  margin-right: 12px;
}

table.jqplot-table-legend,
table.jqplot-cursor-legend {
  background-color: rgba(255, 255, 255, 0.6);
  border: 1px solid #cccccc;
  position: absolute;
  font-size: 0.75em;
}

td.jqplot-table-legend {
  vertical-align: middle;
}


/*
These rules could be used instead of assigning
element styles and relying on js object properties.
*/


/*
td.jqplot-table-legend-swatch {
    padding-top: 0.5em;
    text-align: center;
}

tr.jqplot-table-legend:first td.jqplot-table-legend-swatch {
    padding-top: 0px;
}
*/

td.jqplot-seriesToggle:hover,
td.jqplot-seriesToggle:active {
  cursor: pointer;
}

.jqplot-table-legend .jqplot-series-hidden {
  text-decoration: line-through;
}

div.jqplot-table-legend-swatch-outline {
  border: 1px solid #cccccc;
  padding: 1px;
}

div.jqplot-table-legend-swatch {
  width: 0px;
  height: 0px;
  border-top-width: 5px;
  border-bottom-width: 5px;
  border-left-width: 6px;
  border-right-width: 6px;
  border-top-style: solid;
  border-bottom-style: solid;
  border-left-style: solid;
  border-right-style: solid;
}

.jqplot-title {
  top: 0px;
  left: 0px;
  padding-bottom: 0.5em;
  font-size: 1.2em;
}

table.jqplot-cursor-tooltip {
  border: 1px solid #cccccc;
  font-size: 0.75em;
}

.jqplot-cursor-tooltip {
  border: 1px solid #cccccc;
  font-size: 0.75em;
  white-space: nowrap;
  background: rgba(208, 208, 208, 0.5);
  padding: 1px;
}

.jqplot-highlighter-tooltip,
.jqplot-canvasOverlay-tooltip {
  border: 1px solid #cccccc;
  font-size: 0.75em;
  white-space: nowrap;
  background: rgba(208, 208, 208, 0.5);
  padding: 1px;
}

.jqplot-point-label {
  font-size: 0.75em;
  z-index: 2;
}

td.jqplot-cursor-legend-swatch {
  vertical-align: middle;
  text-align: center;
}

div.jqplot-cursor-legend-swatch {
  width: 1.2em;
  height: 0.7em;
}

.jqplot-error {
  /*   Styles added to the plot target container when there is an error go here.*/
  text-align: center;
}

.jqplot-error-message {
  /*    Styling of the custom error message div goes here.*/
  position: relative;
  top: 46%;
  display: inline-block;
}

div.jqplot-bubble-label {
  font-size: 0.8em;
  /*    background: rgba(90%, 90%, 90%, 0.15);*/
  padding-left: 2px;
  padding-right: 2px;
  color: rgb(20%, 20%, 20%);
}

div.jqplot-bubble-label.jqplot-bubble-label-highlight {
  background: rgba(90%, 90%, 90%, 0.7);
}

div.jqplot-noData-container {
  text-align: center;
  background-color: rgba(96%, 96%, 96%, 0.3);
}

</style>


<script type="text/javascript">//<![CDATA[
$(window).load(function(){
//In order to use keyboard highlight of the coordinates please click somewhere inside the Result frame.
$(document).ready(function() {
// Some simple loops to build up data arrays.
var cosPoints = [];
for (var i = 0; i < 2 * Math.PI; i += 0.4) {
cosPoints.push([i, Math.cos(i)]);
}

var plot3 = $.jqplot('chart', [cosPoints], {
cursor: {
show: true,
showTooltip: true,
showTooltipGridPosition: true,
//  showTooltipDataPosition: false,
showTooltipUnitPosition: false,
useAxesFormatters: false,
// showVerticalLine : true,
followMouse: true
},
title: 'Line Style Options',
// Series options are specified as an array of objects, one object
series: [{
// Change our line width and use a diamond shaped marker.
lineWidth: 2,
showLine: false,
color: 'red',
markerOptions: {
style: 'diamond',
color: 'black'
}
}, {
// Don't show a line, just show markers.
// Make the markers 7 pixels with an 'x' style
showLine: false,
markerOptions: {
size: 7,
style: "x"
}
}, {
      // Use (open) circlular markers.
      markerOptions: {
        style: "circle"
      }
    }, {
      // Use a thicker, 5 pixel line and 10 pixel
      // filled square markers.
      lineWidth: 5,
      markerOptions: {
        style: "filledSquare",
        size: 10
      }
    }]
  });

  $('#chart').bind('jqplotDataClick', function(ev, seriesIndex, pointIndex, data) {
    alert(data);
  });

  var counter = -1; //to start from the very first on first next click, on prev click it will start from last -- and this is how we want it
  $('#buttonPrev').bind("click", function() {
    counter--;
    DoSomeThing(plot3);
  });

  $('#buttonNext').bind("click", function() {
    counter++;
    DoSomeThing(plot3);
  });

  $(document).keydown(function(e) {
    if (e.keyCode == 37) {
      $('#buttonPrev').click();
    } else if (e.keyCode == 39) {
      $('#buttonNext').click();
    }
  });

  function DoSomeThing(plot) {
    // *** highlight point in plot ***
    //console.log(" sth "+ plot.series[0].data[1][1]);
    var seriesIndex = 0; //0 as we have just one series
    var data = plot.series[seriesIndex].data;
    if (counter >= data.length) counter = 0;
    else if (counter < 0) counter = data.length - 1;
    var pointIndex = counter;
    var x = plot.axes.xaxis.series_u2p(data[pointIndex][0]);
    var y = plot.axes.yaxis.series_u2p(data[pointIndex][1]);
    console.log("x= " + x + "  y= " + y);
    var r = 5;
    var drawingCanvas = $(".jqplot-highlight-canvas")[0]; //$(".jqplot-series-canvas")[0];
    var context = drawingCanvas.getContext('2d');
    context.clearRect(0, 0, drawingCanvas.width, drawingCanvas.height); //plot.replot();            
    context.strokeStyle = "#000000";
    context.fillStyle = "#FFFF00";
    context.beginPath();
    context.arc(x, y, r, 0, Math.PI * 2, true);
    context.closePath();
    context.stroke();
    context.fill();
  }
});

});//]]> 

</script>

  

