# paged tables
<h2> Paginated Table</h2>

<style>
    table {
    width: 40em;
    margin: 2em auto;
}

thead {
    background: #000;
    color: #fff;
}

td {
    width: 10em;
    padding: 0.3em;
}

tbody {
    background: #ccc;
}

div.pager {
    text-align: center;
    margin: 1em 0;
}

div.pager span {
    display: inline-block;
    width: 1.8em;
    height: 1.8em;
    line-height: 1.8;
    text-align: center;
    cursor: pointer;
    background: #000;
    color: #fff;
    margin-right: 0.5em;
}

div.pager span.active {
    background: #c00;
}


*, body, button, input, textarea, select {
  text-rendering: optimizeLegibility;
  -moz-osx-font-smoothing: grayscale;
}

body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,form,fieldset,input,textarea,p,blockquote,th,td {
  margin:0;
  padding:0;
}
table {
  border-collapse:collapse;
  border-spacing:0;
}
fieldset,img {
  border:0;
}
address,caption,cite,code,dfn,em,strong,th,var {
  font-style:normal;
  font-weight:normal;
}
ol,ul {
  list-style:none;
}
caption,th {
  text-align:left;
}
h1,h2,h3,h4,h5,h6 {
  font-size:100%;
  font-weight:normal;
}
q:before,q:after {
  content:'';
}
abbr,acronym { border:0;}


body {
  background: #fff;
}
</style>

<script type='text/javascript'>//<![CDATA[
$(function(){
$('td', 'table').each(function(i) {
    $(this).text(i+1);
});



$('table.paginated').each(function() {
    var currentPage = 0;
    var numPerPage = 4;
    var $table = $(this);
    $table.bind('repaginate', function() {
        $table.find('tbody tr').hide().slice(currentPage * numPerPage, (currentPage + 1) * numPerPage).show();
    });
    $table.trigger('repaginate');
    var numRows = $table.find('tbody tr').length;
    var numPages = Math.ceil(numRows / numPerPage);
    var $pager = $('<div class="pager"></div>');
    for (var page = 0; page < numPages; page++) {
        $('<span class="page-number"></span>').text(page + 1).bind('click', {
            newPage: page
        }, function(event) {
            currentPage = event.data['newPage'];
            $table.trigger('repaginate');
            $(this).addClass('active').siblings().removeClass('active');
        }).appendTo($pager).addClass('clickable');
    }
    $pager.insertBefore($table).find('span.page-number:first').addClass('active');
});
});//]]> 

</script>


<table class="paginated">
<thead>
<tr>
<th scope="col">A</th>
<th scope="col">B</th>  
<th scope="col">C</th> 
<th scope="col">D</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>11</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>21</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>31</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>41</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>51</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>61</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>71</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>81</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>91</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>101</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>111</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>121</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>131</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>141</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>151</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>161</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>171</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>181</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>191</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
</tbody>
</table>
